// Extension to language name mapping for syntax highlighting
// Based on common file extensions and language identifiers

pub fn language_for_extension(ext: &str) -> Option<&'static str> {
    let ext = ext.trim_start_matches('.').to_lowercase();
    Some(match ext.as_str() {
        "rs" => "rust",
        "py" | "pyw" | "pyx" => "python",
        "js" | "jsx" | "mjs" | "cjs" => "javascript",
        "ts" | "tsx" | "mts" | "cts" => "typescript",
        "go" => "go",
        "java" | "jsp" => "java",
        "c" | "h" => "c",
        "cpp" | "cxx" | "cc" | "c++" | "hpp" | "hxx" | "hh" => "cpp",
        "rb" | "ruby" => "ruby",
        "php" | "phtml" | "php3" | "php4" | "php5" | "php7" | "phps" => "php",
        "swift" => "swift",
        "kt" | "kts" | "kotlin" => "kotlin",
        "scala" | "sc" => "scala",
        "lua" => "lua",
        "hs" | "lhs" => "haskell",
        "r" | "rdata" | "rds" => "r",
        "ex" | "exs" => "elixir",
        "dart" => "dart",
        "zig" => "zig",
        "sh" | "bash" | "zsh" | "fish" => "bash",
        "pl" | "pm" | "t" => "perl",
        "sql" => "sql",
        "html" | "htm" | "xhtml" => "html",
        "css" | "scss" | "sass" | "less" => "css",
        "json" | "jsonc" => "json",
        "yaml" | "yml" => "yaml",
        "toml" => "toml",
        "md" | "markdown" | "mdown" => "markdown",
        "xml" | "xsl" | "xslt" | "xsd" | "svg" => "xml",
        "dockerfile" | "Dockerfile" => "dockerfile",
        "makefile" | "Makefile" | "mk" => "makefile",
        "cmake" | "cmake.in" => "cmake",
        "gradle" => "gradle",
        "proto" => "protobuf",
        "graphql" | "gql" => "graphql",
        "tex" | "sty" | "cls" | "ltx" => "latex",
        "clj" | "cljs" | "cljc" | "edn" => "clojure",
        "erl" | "hrl" => "erlang",
        "elm" => "elm",
        "fs" | "fsx" | "fsi" => "fsharp",
        "nim" => "nim",
        "crystal" | "cr" => "crystal",
        "tf" | "tfvars" | "hcl" => "terraform",
        "ps1" | "psm1" | "psd1" => "powershell",
        "bat" | "cmd" => "batch",
        "diff" | "patch" => "diff",
        _ => return None,
    })
}

pub fn normalize_language(lang: &str) -> &str {
    match lang {
        "js" | "javascript" | "ecmascript" | "mjs" | "cjs" | "node" => "javascript",
        "ts" | "typescript" | "tsx" | "mts" | "cts" => "typescript",
        "py" | "python" | "python3" => "python",
        "rb" | "ruby" => "ruby",
        "rs" => "rust",
        "go" | "golang" => "go",
        "c" => "c",
        "cpp" | "cxx" | "cc" | "c++" | "hpp" => "cpp",
        "java" => "java",
        "swift" => "swift",
        "kt" | "kts" | "kotlin" => "kotlin",
        "scala" | "sc" => "scala",
        "lua" => "lua",
        "hs" | "haskell" | "lhs" => "haskell",
        "r" | "R" => "r",
        "ex" | "exs" | "elixir" => "elixir",
        "dart" => "dart",
        "zig" => "zig",
        "sh" | "bash" | "zsh" | "shell" => "bash",
        "pl" | "perl" => "perl",
        "sql" => "sql",
        "html" | "htm" => "html",
        "css" => "css",
        "json" => "json",
        "yaml" | "yml" => "yaml",
        "toml" => "toml",
        "md" | "markdown" => "markdown",
        "xml" | "svg" => "xml",
        "clj" | "cljs" | "clojure" => "clojure",
        "php" => "php",
        "dockerfile" | "Dockerfile" | "containerfile" => "dockerfile",
        _ => lang,
    }
}
